/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotecnicassimulacion;

/**
 *
 * @author Kike
 */
public class Alisada extends javax.swing.JFrame {

    /**
     * Creates new form PromedioMovil
     */
    public Alisada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dem1 = new javax.swing.JTextField();
        ali1 = new javax.swing.JTextField();
        err1 = new javax.swing.JTextField();
        dem2 = new javax.swing.JTextField();
        ali2 = new javax.swing.JTextField();
        err2 = new javax.swing.JTextField();
        dem3 = new javax.swing.JTextField();
        ali3 = new javax.swing.JTextField();
        err3 = new javax.swing.JTextField();
        dem4 = new javax.swing.JTextField();
        ali4 = new javax.swing.JTextField();
        err4 = new javax.swing.JTextField();
        dem5 = new javax.swing.JTextField();
        ali5 = new javax.swing.JTextField();
        err5 = new javax.swing.JTextField();
        dem6 = new javax.swing.JTextField();
        ali6 = new javax.swing.JTextField();
        err6 = new javax.swing.JTextField();
        err7 = new javax.swing.JTextField();
        ali7 = new javax.swing.JTextField();
        dem7 = new javax.swing.JTextField();
        dem8 = new javax.swing.JTextField();
        ali8 = new javax.swing.JTextField();
        err8 = new javax.swing.JTextField();
        dem9 = new javax.swing.JTextField();
        ali9 = new javax.swing.JTextField();
        err9 = new javax.swing.JTextField();
        dem10 = new javax.swing.JTextField();
        ali10 = new javax.swing.JTextField();
        err10 = new javax.swing.JTextField();
        dem11 = new javax.swing.JTextField();
        ali11 = new javax.swing.JTextField();
        err11 = new javax.swing.JTextField();
        dem12 = new javax.swing.JTextField();
        ali12 = new javax.swing.JTextField();
        err12 = new javax.swing.JTextField();
        dem13 = new javax.swing.JTextField();
        ali13 = new javax.swing.JTextField();
        err13 = new javax.swing.JTextField();
        dem14 = new javax.swing.JTextField();
        ali14 = new javax.swing.JTextField();
        err14 = new javax.swing.JTextField();
        dem15 = new javax.swing.JTextField();
        ali15 = new javax.swing.JTextField();
        err15 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        alfa1 = new javax.swing.JTextField();
        ali16 = new javax.swing.JTextField();
        err16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dem16 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        ali17 = new javax.swing.JTextField();
        err17 = new javax.swing.JTextField();
        dem17 = new javax.swing.JTextField();
        ali18 = new javax.swing.JTextField();
        err18 = new javax.swing.JTextField();
        dem18 = new javax.swing.JTextField();
        ali19 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        alfa2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        dem19 = new javax.swing.JTextField();
        ali20 = new javax.swing.JTextField();
        err19 = new javax.swing.JTextField();
        dem20 = new javax.swing.JTextField();
        ali21 = new javax.swing.JTextField();
        err20 = new javax.swing.JTextField();
        dem21 = new javax.swing.JTextField();
        ali22 = new javax.swing.JTextField();
        err21 = new javax.swing.JTextField();
        dem22 = new javax.swing.JTextField();
        ali23 = new javax.swing.JTextField();
        err22 = new javax.swing.JTextField();
        dem23 = new javax.swing.JTextField();
        ali24 = new javax.swing.JTextField();
        err23 = new javax.swing.JTextField();
        dem24 = new javax.swing.JTextField();
        ali25 = new javax.swing.JTextField();
        err24 = new javax.swing.JTextField();
        dem25 = new javax.swing.JTextField();
        ali26 = new javax.swing.JTextField();
        err25 = new javax.swing.JTextField();
        dem26 = new javax.swing.JTextField();
        ali27 = new javax.swing.JTextField();
        err26 = new javax.swing.JTextField();
        err27 = new javax.swing.JTextField();
        dem27 = new javax.swing.JTextField();
        err28 = new javax.swing.JTextField();
        ali28 = new javax.swing.JTextField();
        ali29 = new javax.swing.JTextField();
        err29 = new javax.swing.JTextField();
        dem28 = new javax.swing.JTextField();
        dem29 = new javax.swing.JTextField();
        ali30 = new javax.swing.JTextField();
        err30 = new javax.swing.JTextField();
        dem30 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALISADA Y SUAVIZACIÓN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALISADA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEMANDA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ERROR");

        dem1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem1.setText("0");

        ali1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem2.setText("0");

        ali2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem3.setText("0");

        ali3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem4.setText("0");

        ali4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem5.setText("0");

        ali5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem6.setText("0");

        ali6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem7.setText("0");

        dem8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem8.setText("0");

        ali8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem9.setText("0");

        ali9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem10.setText("0");

        ali10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem11.setText("0");

        ali11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem12.setText("0");

        ali12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem13.setText("0");

        ali13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem14.setText("0");

        ali14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem15.setText("0");

        ali15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("15");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("14");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("13");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("12");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("11");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("10");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("9");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("8");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("7");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("6");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("5");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("4");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("2");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("3");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("ALFA 1:");

        alfa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alfa1.setText("0.0");

        ali16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("15");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("14");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("13");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("12");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("11");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("10");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("9");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("8");

        dem16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem16.setText("0");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("7");

        ali17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem17.setText("0");

        ali18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem18.setText("0");

        ali19.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("N");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("ALISADA");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("DEMANDA");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("6");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("5");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("4");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("2");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("3");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("ALFA 2:");

        alfa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alfa2.setText("0.0");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("ERROR");

        dem19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem19.setText("0");

        ali20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err19.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem20.setText("0");

        ali21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem21.setText("0");

        ali22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem22.setText("0");

        ali23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem23.setText("0");

        ali24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem24.setText("0");

        ali25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem25.setText("0");

        ali26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem26.setText("0");

        ali27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ali27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ali27ActionPerformed(evt);
            }
        });

        err26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem27.setText("0");

        err28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali29.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err29.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem28.setText("0");

        dem29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem29.setText("0");

        ali30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        err30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dem30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dem30.setText("0");

        jButton1.setText("Alisada Alfa 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alisada Alfa 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dem15)
                            .addComponent(dem14)
                            .addComponent(dem13)
                            .addComponent(dem12)
                            .addComponent(dem11)
                            .addComponent(dem10)
                            .addComponent(dem9)
                            .addComponent(dem8)
                            .addComponent(dem7)
                            .addComponent(dem6)
                            .addComponent(dem5)
                            .addComponent(dem4)
                            .addComponent(dem2)
                            .addComponent(dem1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(dem3)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ali15)
                                    .addComponent(ali14)
                                    .addComponent(ali13)
                                    .addComponent(ali12)
                                    .addComponent(ali11)
                                    .addComponent(ali10)
                                    .addComponent(ali9)
                                    .addComponent(ali8)
                                    .addComponent(ali7)
                                    .addComponent(ali6)
                                    .addComponent(ali5)
                                    .addComponent(ali4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(ali1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ali3)
                                    .addComponent(ali2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(err2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(err1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(err3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(err4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(alfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dem27)
                            .addComponent(dem26)
                            .addComponent(dem25)
                            .addComponent(dem18)
                            .addComponent(dem17)
                            .addComponent(dem16)
                            .addComponent(dem24)
                            .addComponent(dem23)
                            .addComponent(dem22)
                            .addComponent(dem20)
                            .addComponent(dem19)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dem21)
                            .addComponent(dem29)
                            .addComponent(dem28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ali28)
                                        .addComponent(ali27)
                                        .addComponent(ali26)
                                        .addComponent(ali19)
                                        .addComponent(ali18)
                                        .addComponent(ali17)
                                        .addComponent(ali16)
                                        .addComponent(ali29)
                                        .addComponent(ali25)
                                        .addComponent(ali24)
                                        .addComponent(ali23)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(ali22))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ali20, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ali21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(err20, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(err19, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(err21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(err22, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err27, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err28, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err24, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err25, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err29, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(alfa2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dem30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ali30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(err30, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(alfa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ali15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(alfa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ali16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ali17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ali19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dem28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(ali27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dem27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(ali28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ali20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ali21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(dem16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(dem17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel37))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(dem18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel38))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel36)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(dem19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(dem20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel35))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel34)
                                                    .addComponent(dem21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dem22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ali22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dem23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ali23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dem24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ali24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(err24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dem25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ali25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(err25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dem26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ali26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel26)
                                            .addComponent(err26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(err16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(err17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(err19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(err20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(err21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(err22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(err23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(err28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(err27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dem29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23)
                                        .addComponent(ali29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(err29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dem30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(ali30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        double dem50 = Double.parseDouble(dem1.getText().trim());
        double dem51 = Double.parseDouble(dem2.getText().trim());
        double dem52 = Double.parseDouble(dem3.getText().trim());
        double dem53 = Double.parseDouble(dem4.getText().trim());
        double dem54 = Double.parseDouble(dem5.getText().trim());
        double dem55 = Double.parseDouble(dem6.getText().trim());
        double dem56 = Double.parseDouble(dem7.getText().trim());
        double dem57 = Double.parseDouble(dem8.getText().trim());
        double dem58 = Double.parseDouble(dem9.getText().trim());
        double dem59 = Double.parseDouble(dem10.getText().trim());
        double dem60 = Double.parseDouble(dem11.getText().trim());
        double dem61 = Double.parseDouble(dem12.getText().trim());
        double dem62 = Double.parseDouble(dem13.getText().trim());
        double dem63 = Double.parseDouble(dem14.getText().trim());
        double dem64 = Double.parseDouble(dem15.getText().trim());
        dem16.setText(Double.toString(dem50));
        dem17.setText(Double.toString(dem51));
        dem18.setText(Double.toString(dem52));
        dem19.setText(Double.toString(dem53));
        dem20.setText(Double.toString(dem54));
        dem21.setText(Double.toString(dem55));
        dem22.setText(Double.toString(dem56));
        dem23.setText(Double.toString(dem57));
        dem24.setText(Double.toString(dem58));
        dem25.setText(Double.toString(dem59));
        dem26.setText(Double.toString(dem60));
        dem27.setText(Double.toString(dem61));
        dem28.setText(Double.toString(dem62));
        dem29.setText(Double.toString(dem63));
        dem30.setText(Double.toString(dem64));
        
        double alfa10 = Double.parseDouble(alfa1.getText().trim());
        
        ali2.setText(Double.toString(dem50));
        double a2 = Double.parseDouble(ali2.getText().trim());
        ali3.setText(Double.toString(dem51 * alfa10 + (1 - alfa10)* a2));
        double a3 = Double.parseDouble(ali3.getText().trim());
        ali4.setText(Double.toString(dem52 * alfa10 + (1 - alfa10)* a3));
        double a4 = Double.parseDouble(ali4.getText().trim());
        ali5.setText(Double.toString(dem53 * alfa10 + (1 - alfa10)* a4));
        double a5 = Double.parseDouble(ali5.getText().trim());
        ali6.setText(Double.toString(dem54 * alfa10 + (1 - alfa10)* a5));
        double a6 = Double.parseDouble(ali6.getText().trim());
        ali7.setText(Double.toString(dem55 * alfa10 + (1 - alfa10)* a6));
        double a7 = Double.parseDouble(ali7.getText().trim());
        ali8.setText(Double.toString(dem56 * alfa10 + (1 - alfa10)* a7));
        double a8 = Double.parseDouble(ali8.getText().trim());
        ali9.setText(Double.toString(dem57 * alfa10 + (1 - alfa10)* a8));
        double a9 = Double.parseDouble(ali9.getText().trim());
        ali10.setText(Double.toString(dem58 * alfa10 + (1 - alfa10)* a9));
        double a10 = Double.parseDouble(ali10.getText().trim());
        ali11.setText(Double.toString(dem59 * alfa10 + (1 - alfa10)* a10));
        double a11 = Double.parseDouble(ali11.getText().trim());
        ali12.setText(Double.toString(dem60 * alfa10 + (1 - alfa10)* a11));
        double a12 = Double.parseDouble(ali12.getText().trim());
        ali13.setText(Double.toString(dem61 * alfa10 + (1 - alfa10)* a12));
        double a13 = Double.parseDouble(ali13.getText().trim());
        ali14.setText(Double.toString(dem62 * alfa10 + (1 - alfa10)* a13));
        double a14 = Double.parseDouble(ali14.getText().trim());
        ali15.setText(Double.toString(dem63 * alfa10 + (1 - alfa10)* a14));
        double a15 = Double.parseDouble(ali15.getText().trim());
        
        err2.setText(Double.toString(dem51 - a2));
        err3.setText(Double.toString(dem52 - a3));
        err4.setText(Double.toString(dem53 - a4));
        err5.setText(Double.toString(dem54 - a5));
        err6.setText(Double.toString(dem55 - a6));
        err7.setText(Double.toString(dem56 - a7));
        err8.setText(Double.toString(dem57 - a8));
        err9.setText(Double.toString(dem58 - a9));
        err10.setText(Double.toString(dem59 - a10));
        err11.setText(Double.toString(dem60 - a11));
        err12.setText(Double.toString(dem61 - a12));
        err13.setText(Double.toString(dem62 - a13));
        err14.setText(Double.toString(dem63 - a14));
        err15.setText(Double.toString(dem64 - a15));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ali27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ali27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ali27ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double alfa20 = Double.parseDouble(alfa2.getText().trim());
        
        //double dem50 = Double.parseDouble(dem16.getText().trim());
        double dem50 = Double.parseDouble(dem16.getText().trim());
        double dem51 = Double.parseDouble(dem17.getText().trim());
        double dem52 = Double.parseDouble(dem18.getText().trim());
        double dem53 = Double.parseDouble(dem19.getText().trim());
        double dem54 = Double.parseDouble(dem20.getText().trim());
        double dem55 = Double.parseDouble(dem21.getText().trim());
        double dem56 = Double.parseDouble(dem22.getText().trim());
        double dem57 = Double.parseDouble(dem23.getText().trim());
        double dem58 = Double.parseDouble(dem24.getText().trim());
        double dem59 = Double.parseDouble(dem25.getText().trim());
        double dem60 = Double.parseDouble(dem26.getText().trim());
        double dem61 = Double.parseDouble(dem27.getText().trim());
        double dem62 = Double.parseDouble(dem28.getText().trim());
        double dem63 = Double.parseDouble(dem29.getText().trim());
        double dem64 = Double.parseDouble(dem30.getText().trim());
        
        //ali17.setText(Double.toString(dem50));
        ali17.setText(Double.toString(dem50));
        double a2 = Double.parseDouble(ali17.getText().trim());
        ali18.setText(Double.toString(dem51 * alfa20 + (1 - alfa20)* a2));
        double a3 = Double.parseDouble(ali18.getText().trim());
        ali19.setText(Double.toString(dem52 * alfa20 + (1 - alfa20)* a3));
        double a4 = Double.parseDouble(ali19.getText().trim());
        ali20.setText(Double.toString(dem53 * alfa20 + (1 - alfa20)* a4));
        double a5 = Double.parseDouble(ali20.getText().trim());
        ali21.setText(Double.toString(dem54 * alfa20 + (1 - alfa20)* a5));
        double a6 = Double.parseDouble(ali21.getText().trim());
        ali22.setText(Double.toString(dem55 * alfa20 + (1 - alfa20)* a6));
        double a7 = Double.parseDouble(ali22.getText().trim());
        ali23.setText(Double.toString(dem56 * alfa20 + (1 - alfa20)* a7));
        double a8 = Double.parseDouble(ali23.getText().trim());
        ali24.setText(Double.toString(dem57 * alfa20 + (1 - alfa20)* a8));
        double a9 = Double.parseDouble(ali24.getText().trim());
        ali25.setText(Double.toString(dem58 * alfa20 + (1 - alfa20)* a9));
        double a10 = Double.parseDouble(ali25.getText().trim());
        ali26.setText(Double.toString(dem59 * alfa20 + (1 - alfa20)* a10));
        double a11 = Double.parseDouble(ali26.getText().trim());
        ali27.setText(Double.toString(dem60 * alfa20 + (1 - alfa20)* a11));
        double a12 = Double.parseDouble(ali27.getText().trim());
        ali28.setText(Double.toString(dem61 * alfa20 + (1 - alfa20)* a12));
        double a13 = Double.parseDouble(ali28.getText().trim());
        ali29.setText(Double.toString(dem62 * alfa20 + (1 - alfa20)* a13));
        double a14 = Double.parseDouble(ali29.getText().trim());
        ali30.setText(Double.toString(dem63 * alfa20 + (1 - alfa20)* a14));
        double a15 = Double.parseDouble(ali30.getText().trim());
        
        err17.setText(Double.toString(dem51 - a2));
        err18.setText(Double.toString(dem52 - a3));
        err19.setText(Double.toString(dem53 - a4));
        err20.setText(Double.toString(dem54 - a5));
        err21.setText(Double.toString(dem55 - a6));
        err22.setText(Double.toString(dem56 - a7));
        err23.setText(Double.toString(dem57 - a8));
        err24.setText(Double.toString(dem58 - a9));
        err25.setText(Double.toString(dem59 - a10));
        err26.setText(Double.toString(dem60 - a11));
        err27.setText(Double.toString(dem61 - a12));
        err28.setText(Double.toString(dem62 - a13));
        err29.setText(Double.toString(dem63 - a14));
        err30.setText(Double.toString(dem64 - a15));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alisada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alisada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alisada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alisada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alisada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alfa1;
    private javax.swing.JTextField alfa2;
    private javax.swing.JTextField ali1;
    private javax.swing.JTextField ali10;
    private javax.swing.JTextField ali11;
    private javax.swing.JTextField ali12;
    private javax.swing.JTextField ali13;
    private javax.swing.JTextField ali14;
    private javax.swing.JTextField ali15;
    private javax.swing.JTextField ali16;
    private javax.swing.JTextField ali17;
    private javax.swing.JTextField ali18;
    private javax.swing.JTextField ali19;
    private javax.swing.JTextField ali2;
    private javax.swing.JTextField ali20;
    private javax.swing.JTextField ali21;
    private javax.swing.JTextField ali22;
    private javax.swing.JTextField ali23;
    private javax.swing.JTextField ali24;
    private javax.swing.JTextField ali25;
    private javax.swing.JTextField ali26;
    private javax.swing.JTextField ali27;
    private javax.swing.JTextField ali28;
    private javax.swing.JTextField ali29;
    private javax.swing.JTextField ali3;
    private javax.swing.JTextField ali30;
    private javax.swing.JTextField ali4;
    private javax.swing.JTextField ali5;
    private javax.swing.JTextField ali6;
    private javax.swing.JTextField ali7;
    private javax.swing.JTextField ali8;
    private javax.swing.JTextField ali9;
    private javax.swing.JTextField dem1;
    private javax.swing.JTextField dem10;
    private javax.swing.JTextField dem11;
    private javax.swing.JTextField dem12;
    private javax.swing.JTextField dem13;
    private javax.swing.JTextField dem14;
    private javax.swing.JTextField dem15;
    private javax.swing.JTextField dem16;
    private javax.swing.JTextField dem17;
    private javax.swing.JTextField dem18;
    private javax.swing.JTextField dem19;
    private javax.swing.JTextField dem2;
    private javax.swing.JTextField dem20;
    private javax.swing.JTextField dem21;
    private javax.swing.JTextField dem22;
    private javax.swing.JTextField dem23;
    private javax.swing.JTextField dem24;
    private javax.swing.JTextField dem25;
    private javax.swing.JTextField dem26;
    private javax.swing.JTextField dem27;
    private javax.swing.JTextField dem28;
    private javax.swing.JTextField dem29;
    private javax.swing.JTextField dem3;
    private javax.swing.JTextField dem30;
    private javax.swing.JTextField dem4;
    private javax.swing.JTextField dem5;
    private javax.swing.JTextField dem6;
    private javax.swing.JTextField dem7;
    private javax.swing.JTextField dem8;
    private javax.swing.JTextField dem9;
    private javax.swing.JTextField err1;
    private javax.swing.JTextField err10;
    private javax.swing.JTextField err11;
    private javax.swing.JTextField err12;
    private javax.swing.JTextField err13;
    private javax.swing.JTextField err14;
    private javax.swing.JTextField err15;
    private javax.swing.JTextField err16;
    private javax.swing.JTextField err17;
    private javax.swing.JTextField err18;
    private javax.swing.JTextField err19;
    private javax.swing.JTextField err2;
    private javax.swing.JTextField err20;
    private javax.swing.JTextField err21;
    private javax.swing.JTextField err22;
    private javax.swing.JTextField err23;
    private javax.swing.JTextField err24;
    private javax.swing.JTextField err25;
    private javax.swing.JTextField err26;
    private javax.swing.JTextField err27;
    private javax.swing.JTextField err28;
    private javax.swing.JTextField err29;
    private javax.swing.JTextField err3;
    private javax.swing.JTextField err30;
    private javax.swing.JTextField err4;
    private javax.swing.JTextField err5;
    private javax.swing.JTextField err6;
    private javax.swing.JTextField err7;
    private javax.swing.JTextField err8;
    private javax.swing.JTextField err9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
