/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotecnicassimulacion;

import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kike
 */
public class NumerosAleatorios extends javax.swing.JFrame {

    /**
     * Creates new form NumerosAleatorios
     */
    public NumerosAleatorios() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        double num1;
        double num2;
        double num3;
        double num4;
        double num5;
        double num6;
        double num7;
        double num8;
        double num9;
        double num10;
        double num11;
        double num12;
        double num13;
        double num14;
        double num15;
        double num16;
        double num17;
        double num18;
        double num19;
        double num20;
        double num21;
        double num22;
        double num23;
        double num24;
        
        double num31;
        double num32;
        double num33;
        double num34;
        double num35;
        
        double num36;
        double num37;
        double num38;
        double num39;
        double num40;
        double num41;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        x0 = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        uni0 = new javax.swing.JTextField();
        uni1 = new javax.swing.JTextField();
        uni2 = new javax.swing.JTextField();
        uni3 = new javax.swing.JTextField();
        uni4 = new javax.swing.JTextField();
        uni5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fre0 = new javax.swing.JTextField();
        fre1 = new javax.swing.JTextField();
        fre2 = new javax.swing.JTextField();
        fre3 = new javax.swing.JTextField();
        fre4 = new javax.swing.JTextField();
        freTot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pro0 = new javax.swing.JTextField();
        pro1 = new javax.swing.JTextField();
        pro2 = new javax.swing.JTextField();
        pro3 = new javax.swing.JTextField();
        pro4 = new javax.swing.JTextField();
        proTot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        acu0 = new javax.swing.JTextField();
        acu1 = new javax.swing.JTextField();
        acu2 = new javax.swing.JTextField();
        acu3 = new javax.swing.JTextField();
        acu4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        men0 = new javax.swing.JTextField();
        men1 = new javax.swing.JTextField();
        men2 = new javax.swing.JTextField();
        men3 = new javax.swing.JTextField();
        men4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        may0 = new javax.swing.JTextField();
        may1 = new javax.swing.JTextField();
        may2 = new javax.swing.JTextField();
        may3 = new javax.swing.JTextField();
        may4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NÚMEROS ALEATORIOS CON MÉTODO CONGRUENCIAL");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Números aleatorios - Método Congruencial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Semilla Xo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Multiplicador a:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cons. Aditiva c:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Módulo m:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Generar números ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x0, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(x0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Probabilidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("UNIDAD");

        uni0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uni0.setText("0");
        uni0.setEnabled(false);

        uni1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uni1.setText("1");
        uni1.setEnabled(false);

        uni2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uni2.setText("2");
        uni2.setEnabled(false);

        uni3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uni3.setText("3");
        uni3.setEnabled(false);

        uni4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uni4.setText("4");
        uni4.setEnabled(false);

        uni5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uni5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uni5.setText("TOTAL");
        uni5.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FRECUENCIA");

        fre0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fre0.setText("0");

        fre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fre1.setText("0");

        fre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fre2.setText("0");

        fre3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fre3.setText("0");

        fre4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fre4.setText("0");

        freTot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        freTot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        freTot.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PROBABILIDAD");

        pro0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pro0.setText("0");

        pro1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pro1.setText("0");

        pro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pro2.setText("0");

        pro3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pro3.setText("0");

        pro4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pro4.setText("0");

        proTot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        proTot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proTot.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ACUMULADA");

        acu0.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        acu1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        acu2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        acu3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        acu4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MENOR");

        men0.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        men1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        men2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        men3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        men4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MAYOR");

        may0.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        may1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        may2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        may3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        may4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton2.setText("Frecuencia");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Probabilidad");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(uni2)
                        .addComponent(uni1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addComponent(uni0, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(uni3)
                        .addComponent(uni4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uni5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fre2)
                        .addComponent(fre1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fre0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fre3)
                        .addComponent(fre4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(freTot, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pro2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pro1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pro0)
                    .addComponent(pro3)
                    .addComponent(pro4)
                    .addComponent(proTot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(acu2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acu1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acu0)
                    .addComponent(acu3)
                    .addComponent(acu4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(men2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(men1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(men0)
                    .addComponent(men3)
                    .addComponent(men4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(may2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(may1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(may0)
                    .addComponent(may3)
                    .addComponent(may4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(may0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(may1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(may2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(may3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(may4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(men0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(men1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(men2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(men3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(men4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acu0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fre0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pro0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(freTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(proTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uni0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uni3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uni4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(uni5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        num1 = Double.parseDouble(x0.getText().trim());
        num2 = Double.parseDouble(a.getText().trim());
        num3 = Double.parseDouble(c.getText().trim());
        num4 = Double.parseDouble(m.getText().trim());
                
        num5 = (num1 * num2 + num3) % num4;
        num6 = (num5 * num2 + num3) % num4;
        num7 = (num6 * num2 + num3) % num4;
        num8 = (num7 * num2 + num3) % num4;
        num9 = (num8 * num2 + num3) % num4;
        num10 = (num9 * num2 + num3) % num4;
        num11 = (num10 * num2 + num3) % num4;
        num12 = (num11 * num2 + num3) % num4;
        num13 = (num12 * num2 + num3) % num4;
        num14 = (num13 * num2 + num3) % num4;
        num15 = (num14 * num2 + num3) % num4;
        num16 = (num15 * num2 + num3) % num4;
        num17 = (num16 * num2 + num3) % num4;
        num18 = (num17 * num2 + num3) % num4;
        num19 = (num18 * num2 + num3) % num4;
        num20 = (num19 * num2 + num3) % num4;
        num21 = (num20 * num2 + num3) % num4;
        num22 = (num21 * num2 + num3) % num4;
        num23 = (num22 * num2 + num3) % num4;
        num24 = (num23 * num2 + num3) % num4;
        
        modelo.addColumn("N");
        modelo.addColumn("Xn+1");
        modelo.addColumn("aXn+c % m");
        modelo.addColumn("Num. Aleatorio");
        modelo.addRow(new Object[]{"1",num1, num5, num5/num4});
        modelo.addRow(new Object[]{"2",num5, num6, num6/num4});
        modelo.addRow(new Object[]{"3",num6, num7, num7/num4});
        modelo.addRow(new Object[]{"4",num7, num8, num8/num4});
        modelo.addRow(new Object[]{"5",num8, num9, num9/num4});
        modelo.addRow(new Object[]{"6",num9, num10, num10/num4});
        modelo.addRow(new Object[]{"7",num10, num11, num11/num4});
        modelo.addRow(new Object[]{"8",num11, num12, num12/num4});
        modelo.addRow(new Object[]{"9",num12, num13, num13/num4});
        modelo.addRow(new Object[]{"10",num13, num14, num14/num4});
        modelo.addRow(new Object[]{"11",num14, num15, num15/num4});
        modelo.addRow(new Object[]{"12",num15, num16, num16/num4});
        modelo.addRow(new Object[]{"13",num16, num17, num17/num4});
        modelo.addRow(new Object[]{"14",num17, num18, num18/num4});
        modelo.addRow(new Object[]{"15",num18, num19, num19/num4});
        modelo.addRow(new Object[]{"16",num19, num20, num20/num4});
        modelo.addRow(new Object[]{"17",num20, num21, num21/num4});
        modelo.addRow(new Object[]{"18",num21, num22, num22/num4});
        modelo.addRow(new Object[]{"19",num22, num23, num23/num4});
        modelo.addRow(new Object[]{"20",num23, num24, num24/num4});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#,000");
        
            num31 = Double.parseDouble(fre0.getText().trim());
            num32 = Double.parseDouble(fre1.getText().trim());
            num33 = Double.parseDouble(fre2.getText().trim());
            num34 = Double.parseDouble(fre3.getText().trim());
            num35 = Double.parseDouble(fre4.getText().trim());
            
            num36 = (num31 + num32 + num33 + num34 + num35);
            
            freTot.setText(Double.toString(num36));
            
            pro0.setText(Double.toString((num31 * 100 / num36)/100));
            pro1.setText(Double.toString((num32 * 100 / num36)/100));
            pro2.setText(Double.toString((num33 * 100 / num36)/100));
            pro3.setText(Double.toString((num34 * 100 / num36)/100));
            pro4.setText(Double.toString((num35 * 100 / num36)/100));           

            num37 = Double.parseDouble(pro0.getText().trim());
            num38 = Double.parseDouble(pro1.getText().trim());
            num39 = Double.parseDouble(pro2.getText().trim());
            num40 = Double.parseDouble(pro3.getText().trim());
            num41 = Double.parseDouble(pro4.getText().trim());
            
            proTot.setText(Double.toString(num37 + num38 + num39 + num40 + num41));

            acu0.setText(Double.toString(num37));
            acu1.setText(Double.toString(num37 + num38));
            acu2.setText(Double.toString(num37 + num38 + num39));
            acu3.setText(Double.toString(num37 + num38 + num39 + num40));
            acu4.setText(Double.toString(num37 + num38 + num39 + num40 + num41));
            
            may0.setText(Double.toString(num37));
            may1.setText(Double.toString(num37 + num38));
            may2.setText(Double.toString(num37 + num38 + num39));
            may3.setText(Double.toString(num37 + num38 + num39 + num40));
            may4.setText(Double.toString(num37 + num38 + num39 + num40 + num41));
            
            men0.setText(Double.toString(0));
            men1.setText(Double.toString((num37)+ 0.001));
            men2.setText(Double.toString((num37 + num38)+ 0.001));
            men3.setText(Double.toString((num37 + num38 + num39)+ 0.001));
            men4.setText(Double.toString((num37 + num38 + num39 + num40)+ 0.001));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            num31 = Double.parseDouble(fre0.getText().trim());
            num32 = Double.parseDouble(fre1.getText().trim());
            num33 = Double.parseDouble(fre2.getText().trim());
            num34 = Double.parseDouble(fre3.getText().trim());
            num35 = Double.parseDouble(fre4.getText().trim());
            
            num36 = (num31 + num32 + num33 + num34 + num35);
            
            freTot.setText(Double.toString(num36));
        
            num37 = Double.parseDouble(pro0.getText().trim());
            num38 = Double.parseDouble(pro1.getText().trim());
            num39 = Double.parseDouble(pro2.getText().trim());
            num40 = Double.parseDouble(pro3.getText().trim());
            num41 = Double.parseDouble(pro4.getText().trim());
            
            proTot.setText(Double.toString(num37 + num38 + num39 + num40 + num41));

            acu0.setText(Double.toString(num37));
            acu1.setText(Double.toString(num37 + num38));
            acu2.setText(Double.toString(num37 + num38 + num39));
            acu3.setText(Double.toString(num37 + num38 + num39 + num40));
            acu4.setText(Double.toString(num37 + num38 + num39 + num40 + num41));
            
            may0.setText(Double.toString(num37));
            may1.setText(Double.toString(num37 + num38));
            may2.setText(Double.toString(num37 + num38 + num39));
            may3.setText(Double.toString(num37 + num38 + num39 + num40));
            may4.setText(Double.toString(num37 + num38 + num39 + num40 + num41));
            
            men0.setText(Double.toString(0));
            men1.setText(Double.toString((num37)+ 0.001));
            men2.setText(Double.toString((num37 + num38)+ 0.001));
            men3.setText(Double.toString((num37 + num38 + num39)+ 0.001));
            men4.setText(Double.toString((num37 + num38 + num39 + num40)+ 0.001));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumerosAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumerosAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumerosAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumerosAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumerosAleatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField acu0;
    private javax.swing.JTextField acu1;
    private javax.swing.JTextField acu2;
    private javax.swing.JTextField acu3;
    private javax.swing.JTextField acu4;
    private javax.swing.JTextField c;
    private javax.swing.JTextField fre0;
    private javax.swing.JTextField fre1;
    private javax.swing.JTextField fre2;
    private javax.swing.JTextField fre3;
    private javax.swing.JTextField fre4;
    private javax.swing.JTextField freTot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField m;
    private javax.swing.JTextField may0;
    private javax.swing.JTextField may1;
    private javax.swing.JTextField may2;
    private javax.swing.JTextField may3;
    private javax.swing.JTextField may4;
    private javax.swing.JTextField men0;
    private javax.swing.JTextField men1;
    private javax.swing.JTextField men2;
    private javax.swing.JTextField men3;
    private javax.swing.JTextField men4;
    private javax.swing.JTextField pro0;
    private javax.swing.JTextField pro1;
    private javax.swing.JTextField pro2;
    private javax.swing.JTextField pro3;
    private javax.swing.JTextField pro4;
    private javax.swing.JTextField proTot;
    private javax.swing.JTextField uni0;
    private javax.swing.JTextField uni1;
    private javax.swing.JTextField uni2;
    private javax.swing.JTextField uni3;
    private javax.swing.JTextField uni4;
    private javax.swing.JTextField uni5;
    private javax.swing.JTextField x0;
    // End of variables declaration//GEN-END:variables
}
