/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotecnicassimulacion;

/**
 *
 * @author Kike
 */
public class PromedioMovil extends javax.swing.JFrame {

    /**
     * Creates new form PromedioMovil
     */
    public PromedioMovil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        ti4 = new javax.swing.JTextField();
        ti5 = new javax.swing.JTextField();
        ti6 = new javax.swing.JTextField();
        ti7 = new javax.swing.JTextField();
        ti8 = new javax.swing.JTextField();
        ti9 = new javax.swing.JTextField();
        ti10 = new javax.swing.JTextField();
        ti11 = new javax.swing.JTextField();
        ti12 = new javax.swing.JTextField();
        ti13 = new javax.swing.JTextField();
        ti14 = new javax.swing.JTextField();
        ti15 = new javax.swing.JTextField();
        ppm1 = new javax.swing.JTextField();
        ppm2 = new javax.swing.JTextField();
        ppm3 = new javax.swing.JTextField();
        ppm4 = new javax.swing.JTextField();
        ppm5 = new javax.swing.JTextField();
        ppm6 = new javax.swing.JTextField();
        ppm7 = new javax.swing.JTextField();
        ppm8 = new javax.swing.JTextField();
        ppm9 = new javax.swing.JTextField();
        ppm10 = new javax.swing.JTextField();
        ppm11 = new javax.swing.JTextField();
        ppm12 = new javax.swing.JTextField();
        ppm13 = new javax.swing.JTextField();
        ppm14 = new javax.swing.JTextField();
        ppm15 = new javax.swing.JTextField();
        epm1 = new javax.swing.JTextField();
        epm2 = new javax.swing.JTextField();
        epm3 = new javax.swing.JTextField();
        epm4 = new javax.swing.JTextField();
        epm5 = new javax.swing.JTextField();
        epm6 = new javax.swing.JTextField();
        epm7 = new javax.swing.JTextField();
        epm8 = new javax.swing.JTextField();
        epm9 = new javax.swing.JTextField();
        epm10 = new javax.swing.JTextField();
        epm11 = new javax.swing.JTextField();
        epm12 = new javax.swing.JTextField();
        epm13 = new javax.swing.JTextField();
        epm14 = new javax.swing.JTextField();
        epm15 = new javax.swing.JTextField();
        epc1 = new javax.swing.JTextField();
        epc2 = new javax.swing.JTextField();
        epc3 = new javax.swing.JTextField();
        epc4 = new javax.swing.JTextField();
        epc5 = new javax.swing.JTextField();
        epc6 = new javax.swing.JTextField();
        epc7 = new javax.swing.JTextField();
        epc8 = new javax.swing.JTextField();
        epc9 = new javax.swing.JTextField();
        epc10 = new javax.swing.JTextField();
        epc11 = new javax.swing.JTextField();
        epc12 = new javax.swing.JTextField();
        epc13 = new javax.swing.JTextField();
        epc14 = new javax.swing.JTextField();
        epc15 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ali1 = new javax.swing.JTextField();
        ali2 = new javax.swing.JTextField();
        ali3 = new javax.swing.JTextField();
        ali4 = new javax.swing.JTextField();
        ali5 = new javax.swing.JTextField();
        ali6 = new javax.swing.JTextField();
        ali7 = new javax.swing.JTextField();
        ali8 = new javax.swing.JTextField();
        ali9 = new javax.swing.JTextField();
        ali10 = new javax.swing.JTextField();
        ali11 = new javax.swing.JTextField();
        ali12 = new javax.swing.JTextField();
        ali13 = new javax.swing.JTextField();
        ali14 = new javax.swing.JTextField();
        ali15 = new javax.swing.JTextField();
        alfa1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROMEDIO MÓVIL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TASA DE INTERES");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRONÓSTICO DE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PROMEDIO MÓVIL");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ERROR DEL");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PRONÓSTICO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ERROR DEL PRON.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AL CUADRADO");

        ti1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti1.setText("0");

        ti2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti2.setText("0");

        ti3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti3.setText("0");

        ti4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti4.setText("0");

        ti5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti5.setText("0");

        ti6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti6.setText("0");

        ti7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti7.setText("0");

        ti8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti8.setText("0");

        ti9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti9.setText("0");

        ti10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti10.setText("0");

        ti11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti11.setText("0");

        ti12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti12.setText("0");

        ti13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti13.setText("0");

        ti14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti14.setText("0");

        ti15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti15.setText("0");

        ppm1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ppm15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epm15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        epc15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("12");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("9");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("8");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("7");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("6");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("5");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("4");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("3");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("15");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("14");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("13");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALISADA");

        ali1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ali15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        alfa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alfa1.setText("0.0");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ALFA");

        jButton1.setText("2 Meses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("3 Meses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("4 Meses");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ti13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(ti12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ti4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ti5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ppm2)
                                            .addComponent(ppm3)
                                            .addComponent(ppm4)
                                            .addComponent(ppm5)
                                            .addComponent(ppm6)
                                            .addComponent(ppm7)
                                            .addComponent(ppm8)
                                            .addComponent(ppm9)
                                            .addComponent(ppm10)
                                            .addComponent(ppm11)
                                            .addComponent(ppm12)
                                            .addComponent(ppm13)
                                            .addComponent(ppm15)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ti14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ppm14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(epm2)
                                    .addComponent(epm3)
                                    .addComponent(epm4)
                                    .addComponent(epm5)
                                    .addComponent(epm6)
                                    .addComponent(epm7)
                                    .addComponent(epm8)
                                    .addComponent(epm9)
                                    .addComponent(epm10)
                                    .addComponent(epm11)
                                    .addComponent(epm12)
                                    .addComponent(epm13)
                                    .addComponent(epm14)
                                    .addComponent(epm15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(epc2)
                                    .addComponent(epc3)
                                    .addComponent(epc4)
                                    .addComponent(epc5)
                                    .addComponent(epc6)
                                    .addComponent(epc7)
                                    .addComponent(epc8)
                                    .addComponent(epc9)
                                    .addComponent(epc10)
                                    .addComponent(epc11)
                                    .addComponent(epc12)
                                    .addComponent(epc13)
                                    .addComponent(epc14)
                                    .addComponent(epc15))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ti1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(ppm1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(epm1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(epc1))
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ali15)
                            .addComponent(ali14)
                            .addComponent(ali13)
                            .addComponent(ali12)
                            .addComponent(ali11)
                            .addComponent(ali10)
                            .addComponent(ali9)
                            .addComponent(ali8)
                            .addComponent(ali7)
                            .addComponent(ali6)
                            .addComponent(ali5)
                            .addComponent(ali4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ali1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ali3)
                            .addComponent(ali2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(alfa1)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ti1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(epm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(epc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alfa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ti10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ti11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ppm10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(epm10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(epc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ppm11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(epm11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(epc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppm15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epm15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(epc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ali15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double ti50 = Double.parseDouble(ti1.getText().trim());
        double ti51 = Double.parseDouble(ti2.getText().trim());
        double ti52 = Double.parseDouble(ti3.getText().trim());
        double ti53 = Double.parseDouble(ti4.getText().trim());
        double ti54 = Double.parseDouble(ti5.getText().trim());
        double ti55 = Double.parseDouble(ti6.getText().trim());
        double ti56 = Double.parseDouble(ti7.getText().trim());
        double ti57 = Double.parseDouble(ti8.getText().trim());
        double ti58 = Double.parseDouble(ti9.getText().trim());
        double ti59 = Double.parseDouble(ti10.getText().trim());
        double ti60 = Double.parseDouble(ti11.getText().trim());
        double ti61 = Double.parseDouble(ti12.getText().trim());
        double ti62 = Double.parseDouble(ti13.getText().trim());
        double ti63 = Double.parseDouble(ti14.getText().trim());
        double ti64 = Double.parseDouble(ti15.getText().trim());
        
        ppm3.setText(Double.toString((ti50 + ti51)/2));
        double ppm52 = Double.parseDouble(ppm3.getText().trim());
        ppm4.setText(Double.toString((ti51 + ti52)/2));
        double ppm53 = Double.parseDouble(ppm4.getText().trim());
        ppm5.setText(Double.toString((ti52 + ti53)/2));
        double ppm54 = Double.parseDouble(ppm5.getText().trim());
        ppm6.setText(Double.toString((ti53 + ti54)/2));
        double ppm55 = Double.parseDouble(ppm6.getText().trim());
        ppm7.setText(Double.toString((ti54 + ti55)/2));
        double ppm56 = Double.parseDouble(ppm7.getText().trim());
        ppm8.setText(Double.toString((ti55 + ti56)/2));
        double ppm57 = Double.parseDouble(ppm8.getText().trim());
        ppm9.setText(Double.toString((ti56 + ti57)/2));
        double ppm58 = Double.parseDouble(ppm9.getText().trim());
        ppm10.setText(Double.toString((ti57 + ti58)/2));
        double ppm59 = Double.parseDouble(ppm10.getText().trim());
        ppm11.setText(Double.toString((ti58 + ti59)/2));
        double ppm60 = Double.parseDouble(ppm11.getText().trim());
        ppm12.setText(Double.toString((ti59 + ti60)/2));
        double ppm61 = Double.parseDouble(ppm12.getText().trim());
        ppm13.setText(Double.toString((ti60 + ti61)/2));
        double ppm62 = Double.parseDouble(ppm13.getText().trim());
        ppm14.setText(Double.toString((ti61 + ti62)/2));
        double ppm63 = Double.parseDouble(ppm14.getText().trim());
        ppm15.setText(Double.toString((ti62 + ti63)/2));
        double ppm64 = Double.parseDouble(ppm15.getText().trim());
        
        epm3.setText(Double.toString((ti52 - ppm52)));
        double epm52 = Double.parseDouble(epm3.getText().trim());
        epm4.setText(Double.toString((ti53 - ppm53)));
        double epm53 = Double.parseDouble(epm4.getText().trim());
        epm5.setText(Double.toString((ti54 - ppm54)));
        double epm54 = Double.parseDouble(epm5.getText().trim());
        epm6.setText(Double.toString((ti55 - ppm55)));
        double epm55 = Double.parseDouble(epm6.getText().trim());
        epm7.setText(Double.toString((ti56 - ppm56)));
        double epm56 = Double.parseDouble(epm7.getText().trim());
        epm8.setText(Double.toString((ti57 - ppm57)));
        double epm57 = Double.parseDouble(epm8.getText().trim());
        epm9.setText(Double.toString((ti58 - ppm58)));
        double epm58 = Double.parseDouble(epm9.getText().trim());
        epm10.setText(Double.toString((ti59 - ppm59)));
        double epm59 = Double.parseDouble(epm10.getText().trim());
        epm11.setText(Double.toString((ti60 - ppm60)));
        double epm60 = Double.parseDouble(epm11.getText().trim());
        epm12.setText(Double.toString((ti61 - ppm61)));
        double epm61 = Double.parseDouble(epm12.getText().trim());
        epm13.setText(Double.toString((ti62 - ppm62)));
        double epm62 = Double.parseDouble(epm13.getText().trim());
        epm14.setText(Double.toString((ti63 - ppm63)));
        double epm63 = Double.parseDouble(epm14.getText().trim());
        epm15.setText(Double.toString((ti64 - ppm64)));
        double epm64 = Double.parseDouble(epm15.getText().trim());
        
        epc3.setText(Double.toString((epm52 * epm52)));
        epc4.setText(Double.toString((epm53 * epm53)));
        epc5.setText(Double.toString((epm54 * epm54)));
        epc4.setText(Double.toString((epm53 * epm53)));
        epc5.setText(Double.toString((epm54 * epm54)));
        epc6.setText(Double.toString((epm55 * epm55)));
        epc7.setText(Double.toString((epm56 * epm56)));
        epc8.setText(Double.toString((epm57 * epm57)));
        epc9.setText(Double.toString((epm58 * epm58)));
        epc10.setText(Double.toString((epm59 * epm59)));
        epc11.setText(Double.toString((epm60 * epm60)));
        epc12.setText(Double.toString((epm61 * epm61)));
        epc13.setText(Double.toString((epm62 * epm62)));
        epc14.setText(Double.toString((epm63 * epm63)));
        epc15.setText(Double.toString((epm64 * epm64)));
        
        double alfa10 = Double.parseDouble(alfa1.getText().trim());
        
        ali3.setText(Double.toString(((ppm52))));
        ali4.setText(Double.toString(((ti52 * alfa10) + (1 - alfa10) * ppm52)));
        ali5.setText(Double.toString(((ti53 * alfa10) + (1 - alfa10) * ppm53)));
        ali6.setText(Double.toString(((ti54 * alfa10) + (1 - alfa10) * ppm54)));
        ali7.setText(Double.toString(((ti55 * alfa10) + (1 - alfa10) * ppm55)));
        ali8.setText(Double.toString(((ti56 * alfa10) + (1 - alfa10) * ppm56)));
        ali9.setText(Double.toString(((ti57 * alfa10) + (1 - alfa10) * ppm57)));
        ali10.setText(Double.toString(((ti58 * alfa10) + (1 - alfa10) * ppm58)));
        ali11.setText(Double.toString(((ti59 * alfa10) + (1 - alfa10) * ppm59)));
        ali12.setText(Double.toString(((ti60 * alfa10) + (1 - alfa10) * ppm60)));
        ali13.setText(Double.toString(((ti61 * alfa10) + (1 - alfa10) * ppm61)));
        ali14.setText(Double.toString(((ti62 * alfa10) + (1 - alfa10) * ppm62)));
        ali15.setText(Double.toString(((ti63 * alfa10) + (1 - alfa10) * ppm63)));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double ti50 = Double.parseDouble(ti1.getText().trim());
        double ti51 = Double.parseDouble(ti2.getText().trim());
        double ti52 = Double.parseDouble(ti3.getText().trim());
        double ti53 = Double.parseDouble(ti4.getText().trim());
        double ti54 = Double.parseDouble(ti5.getText().trim());
        double ti55 = Double.parseDouble(ti6.getText().trim());
        double ti56 = Double.parseDouble(ti7.getText().trim());
        double ti57 = Double.parseDouble(ti8.getText().trim());
        double ti58 = Double.parseDouble(ti9.getText().trim());
        double ti59 = Double.parseDouble(ti10.getText().trim());
        double ti60 = Double.parseDouble(ti11.getText().trim());
        double ti61 = Double.parseDouble(ti12.getText().trim());
        double ti62 = Double.parseDouble(ti13.getText().trim());
        double ti63 = Double.parseDouble(ti14.getText().trim());
        double ti64 = Double.parseDouble(ti15.getText().trim());
        
        
        ppm4.setText(Double.toString((ti50 + ti51 + ti52)/3));
        double ppm53 = Double.parseDouble(ppm4.getText().trim());
        ppm5.setText(Double.toString((ti51 + ti52 + ti53)/3));
        double ppm54 = Double.parseDouble(ppm5.getText().trim());
        ppm6.setText(Double.toString((ti52 + ti53 + ti54)/3));
        double ppm55 = Double.parseDouble(ppm6.getText().trim());
        ppm7.setText(Double.toString((ti53 + ti54 + ti55)/2));
        double ppm56 = Double.parseDouble(ppm7.getText().trim());
        ppm8.setText(Double.toString((ti54 + ti55 + ti56)/3));
        double ppm57 = Double.parseDouble(ppm8.getText().trim());
        ppm9.setText(Double.toString((ti55 + ti56 + ti57)/3));
        double ppm58 = Double.parseDouble(ppm9.getText().trim());
        ppm10.setText(Double.toString((ti56 + ti57 + ti58)/3));
        double ppm59 = Double.parseDouble(ppm10.getText().trim());
        ppm11.setText(Double.toString((ti57 + ti58 + ti59)/3));
        double ppm60 = Double.parseDouble(ppm11.getText().trim());
        ppm12.setText(Double.toString((ti58 + ti59 + ti60)/3));
        double ppm61 = Double.parseDouble(ppm12.getText().trim());
        ppm13.setText(Double.toString((ti59 + ti60 + ti61)/3));
        double ppm62 = Double.parseDouble(ppm13.getText().trim());
        ppm14.setText(Double.toString((ti60 + ti61 + ti62)/3));
        double ppm63 = Double.parseDouble(ppm14.getText().trim());
        ppm15.setText(Double.toString((ti61 + ti62 + ti63)/3));
        double ppm64 = Double.parseDouble(ppm15.getText().trim());
        
        epm4.setText(Double.toString((ti53 - ppm53)));
        double epm53 = Double.parseDouble(epm4.getText().trim());
        epm5.setText(Double.toString((ti54 - ppm54)));
        double epm54 = Double.parseDouble(epm5.getText().trim());
        epm6.setText(Double.toString((ti55 - ppm55)));
        double epm55 = Double.parseDouble(epm6.getText().trim());
        epm7.setText(Double.toString((ti56 - ppm56)));
        double epm56 = Double.parseDouble(epm7.getText().trim());
        epm8.setText(Double.toString((ti57 - ppm57)));
        double epm57 = Double.parseDouble(epm8.getText().trim());
        epm9.setText(Double.toString((ti58 - ppm58)));
        double epm58 = Double.parseDouble(epm9.getText().trim());
        epm10.setText(Double.toString((ti59 - ppm59)));
        double epm59 = Double.parseDouble(epm10.getText().trim());
        epm11.setText(Double.toString((ti60 - ppm60)));
        double epm60 = Double.parseDouble(epm11.getText().trim());
        epm12.setText(Double.toString((ti61 - ppm61)));
        double epm61 = Double.parseDouble(epm12.getText().trim());
        epm13.setText(Double.toString((ti62 - ppm62)));
        double epm62 = Double.parseDouble(epm13.getText().trim());
        epm14.setText(Double.toString((ti63 - ppm63)));
        double epm63 = Double.parseDouble(epm14.getText().trim());
        epm15.setText(Double.toString((ti64 - ppm64)));
        double epm64 = Double.parseDouble(epm15.getText().trim());
        
        epc4.setText(Double.toString((epm53 * epm53)));
        epc5.setText(Double.toString((epm54 * epm54)));
        epc6.setText(Double.toString((epm55 * epm55)));
        epc7.setText(Double.toString((epm56 * epm56)));
        epc8.setText(Double.toString((epm57 * epm57)));
        epc9.setText(Double.toString((epm58 * epm58)));
        epc10.setText(Double.toString((epm59 * epm59)));
        epc11.setText(Double.toString((epm60 * epm60)));
        epc12.setText(Double.toString((epm61 * epm61)));
        epc13.setText(Double.toString((epm62 * epm62)));
        epc14.setText(Double.toString((epm63 * epm63)));
        epc15.setText(Double.toString((epm64 * epm64)));
        
        double alfa10 = Double.parseDouble(alfa1.getText().trim());
        
        
        ali4.setText(Double.toString(((ppm53))));
        ali5.setText(Double.toString(((ti53 * alfa10) + (1 - alfa10) * ppm53)));
        ali6.setText(Double.toString(((ti54 * alfa10) + (1 - alfa10) * ppm54)));
        ali7.setText(Double.toString(((ti55 * alfa10) + (1 - alfa10) * ppm55)));
        ali8.setText(Double.toString(((ti56 * alfa10) + (1 - alfa10) * ppm56)));
        ali9.setText(Double.toString(((ti57 * alfa10) + (1 - alfa10) * ppm57)));
        ali10.setText(Double.toString(((ti58 * alfa10) + (1 - alfa10) * ppm58)));
        ali11.setText(Double.toString(((ti59 * alfa10) + (1 - alfa10) * ppm59)));
        ali12.setText(Double.toString(((ti60 * alfa10) + (1 - alfa10) * ppm60)));
        ali13.setText(Double.toString(((ti61 * alfa10) + (1 - alfa10) * ppm61)));
        ali14.setText(Double.toString(((ti62 * alfa10) + (1 - alfa10) * ppm62)));
        ali15.setText(Double.toString(((ti63 * alfa10) + (1 - alfa10) * ppm63)));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double ti50 = Double.parseDouble(ti1.getText().trim());
        double ti51 = Double.parseDouble(ti2.getText().trim());
        double ti52 = Double.parseDouble(ti3.getText().trim());
        double ti53 = Double.parseDouble(ti4.getText().trim());
        double ti54 = Double.parseDouble(ti5.getText().trim());
        double ti55 = Double.parseDouble(ti6.getText().trim());
        double ti56 = Double.parseDouble(ti7.getText().trim());
        double ti57 = Double.parseDouble(ti8.getText().trim());
        double ti58 = Double.parseDouble(ti9.getText().trim());
        double ti59 = Double.parseDouble(ti10.getText().trim());
        double ti60 = Double.parseDouble(ti11.getText().trim());
        double ti61 = Double.parseDouble(ti12.getText().trim());
        double ti62 = Double.parseDouble(ti13.getText().trim());
        double ti63 = Double.parseDouble(ti14.getText().trim());
        double ti64 = Double.parseDouble(ti15.getText().trim());
        
        ppm5.setText(Double.toString((ti50 + ti51 + ti52 + ti53)/4));
        double ppm54 = Double.parseDouble(ppm5.getText().trim());
        ppm6.setText(Double.toString((ti51 + ti52 + ti53 + ti54)/4));
        double ppm55 = Double.parseDouble(ppm6.getText().trim());
        ppm7.setText(Double.toString((ti52 + ti53 + ti54 + ti55)/4));
        double ppm56 = Double.parseDouble(ppm7.getText().trim());
        ppm8.setText(Double.toString((ti53 + ti54 + ti55 + ti56)/4));
        double ppm57 = Double.parseDouble(ppm8.getText().trim());
        ppm9.setText(Double.toString((ti54 + ti55 + ti56 + ti57)/4));
        double ppm58 = Double.parseDouble(ppm9.getText().trim());
        ppm10.setText(Double.toString((ti55 + ti56 + ti57 + ti58)/4));
        double ppm59 = Double.parseDouble(ppm10.getText().trim());
        ppm11.setText(Double.toString((ti56 + ti57 + ti58 + ti59)/4));
        double ppm60 = Double.parseDouble(ppm11.getText().trim());
        ppm12.setText(Double.toString((ti57 + ti58 + ti59 + ti60)/4));
        double ppm61 = Double.parseDouble(ppm12.getText().trim());
        ppm13.setText(Double.toString((ti58 + ti59 + ti60 + ti61)/4));
        double ppm62 = Double.parseDouble(ppm13.getText().trim());
        ppm14.setText(Double.toString((ti59 + ti60 + ti61 + ti62)/4));
        double ppm63 = Double.parseDouble(ppm14.getText().trim());
        ppm15.setText(Double.toString((ti60 + ti61 + ti62 + ti63)/4));
        double ppm64 = Double.parseDouble(ppm15.getText().trim());
        
        epm5.setText(Double.toString((ti54 - ppm54)));
        double epm54 = Double.parseDouble(epm5.getText().trim());
        epm6.setText(Double.toString((ti55 - ppm55)));
        double epm55 = Double.parseDouble(epm6.getText().trim());
        epm7.setText(Double.toString((ti56 - ppm56)));
        double epm56 = Double.parseDouble(epm7.getText().trim());
        epm8.setText(Double.toString((ti57 - ppm57)));
        double epm57 = Double.parseDouble(epm8.getText().trim());
        epm9.setText(Double.toString((ti58 - ppm58)));
        double epm58 = Double.parseDouble(epm9.getText().trim());
        epm10.setText(Double.toString((ti59 - ppm59)));
        double epm59 = Double.parseDouble(epm10.getText().trim());
        epm11.setText(Double.toString((ti60 - ppm60)));
        double epm60 = Double.parseDouble(epm11.getText().trim());
        epm12.setText(Double.toString((ti61 - ppm61)));
        double epm61 = Double.parseDouble(epm12.getText().trim());
        epm13.setText(Double.toString((ti62 - ppm62)));
        double epm62 = Double.parseDouble(epm13.getText().trim());
        epm14.setText(Double.toString((ti63 - ppm63)));
        double epm63 = Double.parseDouble(epm14.getText().trim());
        epm15.setText(Double.toString((ti64 - ppm64)));
        double epm64 = Double.parseDouble(epm15.getText().trim());        
        
        epc5.setText(Double.toString((epm54 * epm54)));
        epc6.setText(Double.toString((epm55 * epm55)));
        epc7.setText(Double.toString((epm56 * epm56)));
        epc8.setText(Double.toString((epm57 * epm57)));
        epc9.setText(Double.toString((epm58 * epm58)));
        epc10.setText(Double.toString((epm59 * epm59)));
        epc11.setText(Double.toString((epm60 * epm60)));
        epc12.setText(Double.toString((epm61 * epm61)));
        epc13.setText(Double.toString((epm62 * epm62)));
        epc14.setText(Double.toString((epm63 * epm63)));
        epc15.setText(Double.toString((epm64 * epm64)));
        
        double alfa10 = Double.parseDouble(alfa1.getText().trim());        
        
        ali5.setText(Double.toString(((ppm54))));
        ali6.setText(Double.toString(((ti54 * alfa10) + (1 - alfa10) * ppm54)));
        ali7.setText(Double.toString(((ti55 * alfa10) + (1 - alfa10) * ppm55)));
        ali8.setText(Double.toString(((ti56 * alfa10) + (1 - alfa10) * ppm56)));
        ali9.setText(Double.toString(((ti57 * alfa10) + (1 - alfa10) * ppm57)));
        ali10.setText(Double.toString(((ti58 * alfa10) + (1 - alfa10) * ppm58)));
        ali11.setText(Double.toString(((ti59 * alfa10) + (1 - alfa10) * ppm59)));
        ali12.setText(Double.toString(((ti60 * alfa10) + (1 - alfa10) * ppm60)));
        ali13.setText(Double.toString(((ti61 * alfa10) + (1 - alfa10) * ppm61)));
        ali14.setText(Double.toString(((ti62 * alfa10) + (1 - alfa10) * ppm62)));
        ali15.setText(Double.toString(((ti63 * alfa10) + (1 - alfa10) * ppm63)));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromedioMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromedioMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromedioMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromedioMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromedioMovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alfa1;
    private javax.swing.JTextField ali1;
    private javax.swing.JTextField ali10;
    private javax.swing.JTextField ali11;
    private javax.swing.JTextField ali12;
    private javax.swing.JTextField ali13;
    private javax.swing.JTextField ali14;
    private javax.swing.JTextField ali15;
    private javax.swing.JTextField ali2;
    private javax.swing.JTextField ali3;
    private javax.swing.JTextField ali4;
    private javax.swing.JTextField ali5;
    private javax.swing.JTextField ali6;
    private javax.swing.JTextField ali7;
    private javax.swing.JTextField ali8;
    private javax.swing.JTextField ali9;
    private javax.swing.JTextField epc1;
    private javax.swing.JTextField epc10;
    private javax.swing.JTextField epc11;
    private javax.swing.JTextField epc12;
    private javax.swing.JTextField epc13;
    private javax.swing.JTextField epc14;
    private javax.swing.JTextField epc15;
    private javax.swing.JTextField epc2;
    private javax.swing.JTextField epc3;
    private javax.swing.JTextField epc4;
    private javax.swing.JTextField epc5;
    private javax.swing.JTextField epc6;
    private javax.swing.JTextField epc7;
    private javax.swing.JTextField epc8;
    private javax.swing.JTextField epc9;
    private javax.swing.JTextField epm1;
    private javax.swing.JTextField epm10;
    private javax.swing.JTextField epm11;
    private javax.swing.JTextField epm12;
    private javax.swing.JTextField epm13;
    private javax.swing.JTextField epm14;
    private javax.swing.JTextField epm15;
    private javax.swing.JTextField epm2;
    private javax.swing.JTextField epm3;
    private javax.swing.JTextField epm4;
    private javax.swing.JTextField epm5;
    private javax.swing.JTextField epm6;
    private javax.swing.JTextField epm7;
    private javax.swing.JTextField epm8;
    private javax.swing.JTextField epm9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ppm1;
    private javax.swing.JTextField ppm10;
    private javax.swing.JTextField ppm11;
    private javax.swing.JTextField ppm12;
    private javax.swing.JTextField ppm13;
    private javax.swing.JTextField ppm14;
    private javax.swing.JTextField ppm15;
    private javax.swing.JTextField ppm2;
    private javax.swing.JTextField ppm3;
    private javax.swing.JTextField ppm4;
    private javax.swing.JTextField ppm5;
    private javax.swing.JTextField ppm6;
    private javax.swing.JTextField ppm7;
    private javax.swing.JTextField ppm8;
    private javax.swing.JTextField ppm9;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti10;
    private javax.swing.JTextField ti11;
    private javax.swing.JTextField ti12;
    private javax.swing.JTextField ti13;
    private javax.swing.JTextField ti14;
    private javax.swing.JTextField ti15;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    private javax.swing.JTextField ti4;
    private javax.swing.JTextField ti5;
    private javax.swing.JTextField ti6;
    private javax.swing.JTextField ti7;
    private javax.swing.JTextField ti8;
    private javax.swing.JTextField ti9;
    // End of variables declaration//GEN-END:variables
}
