/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotecnicassimulacion;

/**
 *
 * @author Kike
 */
public class RegresionLineal extends javax.swing.JFrame {

    /**
     * Creates new form RegresionLineal
     */
    public RegresionLineal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nx2 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        x4 = new javax.swing.JTextField();
        x5 = new javax.swing.JTextField();
        x6 = new javax.swing.JTextField();
        x7 = new javax.swing.JTextField();
        x8 = new javax.swing.JTextField();
        x9 = new javax.swing.JTextField();
        x10 = new javax.swing.JTextField();
        x11 = new javax.swing.JTextField();
        x12 = new javax.swing.JTextField();
        x13 = new javax.swing.JTextField();
        x14 = new javax.swing.JTextField();
        x15 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        totX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        y1 = new javax.swing.JTextField();
        y2 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        y4 = new javax.swing.JTextField();
        y5 = new javax.swing.JTextField();
        y6 = new javax.swing.JTextField();
        y7 = new javax.swing.JTextField();
        y8 = new javax.swing.JTextField();
        y9 = new javax.swing.JTextField();
        y10 = new javax.swing.JTextField();
        y11 = new javax.swing.JTextField();
        y12 = new javax.swing.JTextField();
        y13 = new javax.swing.JTextField();
        y14 = new javax.swing.JTextField();
        y15 = new javax.swing.JTextField();
        totY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        xc1 = new javax.swing.JTextField();
        xc2 = new javax.swing.JTextField();
        xc3 = new javax.swing.JTextField();
        xc4 = new javax.swing.JTextField();
        xc5 = new javax.swing.JTextField();
        xc6 = new javax.swing.JTextField();
        xc7 = new javax.swing.JTextField();
        xc8 = new javax.swing.JTextField();
        xc9 = new javax.swing.JTextField();
        xc10 = new javax.swing.JTextField();
        xc11 = new javax.swing.JTextField();
        xc12 = new javax.swing.JTextField();
        xc13 = new javax.swing.JTextField();
        xc14 = new javax.swing.JTextField();
        xc15 = new javax.swing.JTextField();
        totXC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        xy1 = new javax.swing.JTextField();
        xy2 = new javax.swing.JTextField();
        xy3 = new javax.swing.JTextField();
        xy4 = new javax.swing.JTextField();
        xy5 = new javax.swing.JTextField();
        xy6 = new javax.swing.JTextField();
        xy7 = new javax.swing.JTextField();
        xy8 = new javax.swing.JTextField();
        xy9 = new javax.swing.JTextField();
        xy10 = new javax.swing.JTextField();
        xy11 = new javax.swing.JTextField();
        xy12 = new javax.swing.JTextField();
        xy13 = new javax.swing.JTextField();
        xy14 = new javax.swing.JTextField();
        xy15 = new javax.swing.JTextField();
        totXY = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yc1 = new javax.swing.JTextField();
        yc2 = new javax.swing.JTextField();
        yc3 = new javax.swing.JTextField();
        yc4 = new javax.swing.JTextField();
        yc5 = new javax.swing.JTextField();
        yc6 = new javax.swing.JTextField();
        yc7 = new javax.swing.JTextField();
        yc8 = new javax.swing.JTextField();
        yc9 = new javax.swing.JTextField();
        yc10 = new javax.swing.JTextField();
        yc11 = new javax.swing.JTextField();
        yc12 = new javax.swing.JTextField();
        yc13 = new javax.swing.JTextField();
        yc14 = new javax.swing.JTextField();
        yc15 = new javax.swing.JTextField();
        totYC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        valorAct = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a0 = new javax.swing.JTextField();
        nuevox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        valory = new javax.swing.JTextField();
        valorx = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        nx1 = new javax.swing.JTextField();
        nx3 = new javax.swing.JTextField();
        nx4 = new javax.swing.JTextField();
        nx5 = new javax.swing.JTextField();
        nx6 = new javax.swing.JTextField();
        nx7 = new javax.swing.JTextField();
        nx8 = new javax.swing.JTextField();
        nx9 = new javax.swing.JTextField();
        nx10 = new javax.swing.JTextField();
        nx11 = new javax.swing.JTextField();
        nx12 = new javax.swing.JTextField();
        nx13 = new javax.swing.JTextField();
        nx14 = new javax.swing.JTextField();
        nx15 = new javax.swing.JTextField();
        ny2 = new javax.swing.JTextField();
        ny1 = new javax.swing.JTextField();
        ny3 = new javax.swing.JTextField();
        ny4 = new javax.swing.JTextField();
        ny5 = new javax.swing.JTextField();
        ny6 = new javax.swing.JTextField();
        ny7 = new javax.swing.JTextField();
        ny8 = new javax.swing.JTextField();
        ny9 = new javax.swing.JTextField();
        ny10 = new javax.swing.JTextField();
        ny11 = new javax.swing.JTextField();
        ny12 = new javax.swing.JTextField();
        ny13 = new javax.swing.JTextField();
        ny14 = new javax.swing.JTextField();
        ny15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGRESIÓN LINEAL");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("4");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("3");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("15");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("14");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("13");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("12");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("9");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("8");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("7");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("6");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("5");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Valor X");

        nx2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx2.setText("0");

        x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x2.setText("0");

        x3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x3.setText("0");

        x4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x4.setText("0");

        x5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x5.setText("0");

        x6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x6.setText("0");

        x7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x7.setText("0");

        x8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x8.setText("0");

        x9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x9.setText("0");

        x10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x10.setText("0");

        x11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x11.setText("0");

        x12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x12.setText("0");

        x13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x13.setText("0");

        x14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x14.setText("0");

        x15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x15.setText("0");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tot:");

        totX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totX.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor Y");

        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y1.setText("0");

        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y2.setText("0");

        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y3.setText("0");

        y4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y4.setText("0");

        y5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y5.setText("0");

        y6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y6.setText("0");

        y7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y7.setText("0");

        y8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y8.setText("0");

        y9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y9.setText("0");

        y10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y10.setText("0");

        y11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y11.setText("0");

        y12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y12.setText("0");

        y13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y13.setText("0");

        y14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y14.setText("0");

        y15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y15.setText("0");

        totY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totY.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor X^2");

        xc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc1.setText("0");

        xc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc2.setText("0");

        xc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc3.setText("0");

        xc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc4.setText("0");

        xc5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc5.setText("0");

        xc6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc6.setText("0");

        xc7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc7.setText("0");

        xc8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc8.setText("0");

        xc9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc9.setText("0");

        xc10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc10.setText("0");

        xc11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc11.setText("0");

        xc12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc12.setText("0");

        xc13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc13.setText("0");

        xc14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc14.setText("0");

        xc15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc15.setText("0");

        totXC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totXC.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Valor XY");

        xy1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy1.setText("0");

        xy2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy2.setText("0");

        xy3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy3.setText("0");

        xy4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy4.setText("0");

        xy5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy5.setText("0");

        xy6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy6.setText("0");

        xy7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy7.setText("0");

        xy8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy8.setText("0");

        xy9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy9.setText("0");

        xy10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy10.setText("0");

        xy11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy11.setText("0");

        xy12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy12.setText("0");

        xy13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy13.setText("0");

        xy14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy14.setText("0");

        xy15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xy15.setText("0");

        totXY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totXY.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Valor Y^2");

        yc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc1.setText("0");

        yc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc2.setText("0");

        yc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc3.setText("0");

        yc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc4.setText("0");

        yc5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc5.setText("0");

        yc6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc6.setText("0");

        yc7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc7.setText("0");

        yc8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc8.setText("0");

        yc9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc9.setText("0");

        yc10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc10.setText("0");

        yc11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc11.setText("0");

        yc12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc12.setText("0");

        yc13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc13.setText("0");

        yc14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc14.setText("0");

        yc15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yc15.setText("0");

        totYC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totYC.setText("0");

        jButton1.setText("Generar nuevo numero");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Colocar N para generar a0 y a1");

        valorAct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorAct.setText("0");

        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1.setText("0");

        a0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a0.setText("0");

        nuevox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevox.setText("0");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("*");

        jLabel9.setText("+");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("a1");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Nuevo valor Y");
        jLabel27.setToolTipText("");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("a0");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Valor X a gen.");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Nuevo valor X");
        jLabel30.setToolTipText("");

        jButton2.setText("Generar Sumatoria");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Nuevo Valor X");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Nuevo Valor Y");

        x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x1.setText("0");

        nx1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx1.setText("0");

        nx3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx3.setText("0");

        nx4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx4.setText("0");

        nx5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx5.setText("0");

        nx6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx6.setText("0");

        nx7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx7.setText("0");

        nx8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx8.setText("0");

        nx9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx9.setText("0");

        nx10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx10.setText("0");

        nx11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx11.setText("0");

        nx12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx12.setText("0");

        nx13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx13.setText("0");

        nx14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx14.setText("0");

        nx15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nx15.setText("0");

        ny2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny2.setText("0");

        ny1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny1.setText("0");

        ny3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny3.setText("0");

        ny4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny4.setText("0");

        ny5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny5.setText("0");

        ny6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny6.setText("0");

        ny7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny7.setText("0");

        ny8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny8.setText("0");

        ny9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny9.setText("0");

        ny10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny10.setText("0");

        ny11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny11.setText("0");

        ny12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny12.setText("0");

        ny13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny13.setText("0");

        ny14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny14.setText("0");

        ny15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ny15.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(nx1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(nx2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xc3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xy3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yc3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(valorAct, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nx3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nx4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nx5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nx6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ny3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ny4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ny5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ny6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nx7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(a0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nuevox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(nx8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(nx9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xc11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xc15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xy11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xy15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yc11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valorx, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(valory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nx10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nx11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nx12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nx13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ny10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ny11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ny12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ny13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(totX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(totY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(totXC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(totXY, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(totYC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(nx14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(nx15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel21))
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ny1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel19))
                    .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(nx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ny2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel16)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(y3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(xc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(xy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(yc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(valorAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ny3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(y8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(xc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(xy8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(yc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26))
                    .addComponent(nx7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ny7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13))
                    .addComponent(x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xy9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(nuevox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nx8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ny8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12))
                    .addComponent(x10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xy10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(nx9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ny9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel24)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(y15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xy11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(xy15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel27))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(nx10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nx11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nx12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nx13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ny10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ny13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(totX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(totY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(totXC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(totXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(totYC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nx14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ny14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nx15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ny15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double numx1 = Double.parseDouble(x1.getText().trim());
        double numx2 = Double.parseDouble(x2.getText().trim());
        double numx3 = Double.parseDouble(x3.getText().trim());
        double numx4 = Double.parseDouble(x4.getText().trim());
        double numx5 = Double.parseDouble(x5.getText().trim());
        double numx6 = Double.parseDouble(x6.getText().trim());
        double numx7 = Double.parseDouble(x7.getText().trim());
        double numx8 = Double.parseDouble(x8.getText().trim());
        double numx9 = Double.parseDouble(x9.getText().trim());
        double numx10 = Double.parseDouble(x10.getText().trim());
        double numx11 = Double.parseDouble(x11.getText().trim());
        double numx12 = Double.parseDouble(x12.getText().trim());
        double numx13 = Double.parseDouble(x13.getText().trim());
        double numx14 = Double.parseDouble(x14.getText().trim());
        double numx15 = Double.parseDouble(x15.getText().trim());
        totX.setText(Double.toString((numx1 + numx2 + numx3 + numx4 + numx5 + numx6 + numx7 + numx8 + numx9
                + numx10 + numx11 + numx12 + numx13 + numx14 + numx15)));
        double x = Double.parseDouble(totX.getText().trim());
        
        double numy1 = Double.parseDouble(y1.getText().trim());
        double numy2 = Double.parseDouble(y2.getText().trim());
        double numy3 = Double.parseDouble(y3.getText().trim());
        double numy4 = Double.parseDouble(y4.getText().trim());
        double numy5 = Double.parseDouble(y5.getText().trim());
        double numy6 = Double.parseDouble(y6.getText().trim());
        double numy7 = Double.parseDouble(y7.getText().trim());
        double numy8 = Double.parseDouble(y8.getText().trim());
        double numy9 = Double.parseDouble(y9.getText().trim());
        double numy10 = Double.parseDouble(y10.getText().trim());
        double numy11 = Double.parseDouble(y11.getText().trim());
        double numy12 = Double.parseDouble(y12.getText().trim());
        double numy13 = Double.parseDouble(y13.getText().trim());
        double numy14 = Double.parseDouble(y14.getText().trim());
        double numy15 = Double.parseDouble(y15.getText().trim());
        totY.setText(Double.toString((numy1 + numy2 + numy3 + numy4 + numy5 + numy6 + numy7 + numy8 + numy9
                + numy10 + numy11 + numy12 + numy13 + numy14 + numy15)));
        double y = Double.parseDouble(totY.getText().trim());
        
        xc1.setText(Double.toString(numx1 * numx1));
        double numxc1 = Double.parseDouble(xc1.getText().trim());
        xc2.setText(Double.toString(numx2 * numx2));
        double numxc2 = Double.parseDouble(xc2.getText().trim());
        xc3.setText(Double.toString(numx3 * numx3));
        double numxc3 = Double.parseDouble(xc3.getText().trim());
        xc4.setText(Double.toString(numx4 * numx4));
        double numxc4 = Double.parseDouble(xc4.getText().trim());
        xc5.setText(Double.toString(numx5 * numx5));
        double numxc5 = Double.parseDouble(xc5.getText().trim());
        xc6.setText(Double.toString(numx6 * numx6));
        double numxc6 = Double.parseDouble(xc6.getText().trim());
        xc7.setText(Double.toString(numx7 * numx7));
        double numxc7 = Double.parseDouble(xc7.getText().trim());
        xc8.setText(Double.toString(numx8 * numx8));
        double numxc8 = Double.parseDouble(xc8.getText().trim());
        xc9.setText(Double.toString(numx9 * numx9));
        double numxc9 = Double.parseDouble(xc9.getText().trim());
        xc10.setText(Double.toString(numx10 * numx10));
        double numxc10 = Double.parseDouble(xc10.getText().trim());
        xc11.setText(Double.toString(numx11 * numx11));
        double numxc11 = Double.parseDouble(xc11.getText().trim());
        xc12.setText(Double.toString(numx12 * numx12));
        double numxc12 = Double.parseDouble(xc12.getText().trim());
        xc13.setText(Double.toString(numx13 * numx13));
        double numxc13 = Double.parseDouble(xc13.getText().trim());
        xc14.setText(Double.toString(numx14 * numx14));
        double numxc14 = Double.parseDouble(xc14.getText().trim());
        xc15.setText(Double.toString(numx15 * numx15));
        double numxc15 = Double.parseDouble(xc15.getText().trim());
        totXC.setText(Double.toString((numxc1 + numxc2 + numxc3 + numxc4 + numxc5 + numxc6 + numxc7 + numxc8
                + numxc9 + numxc10 + numxc11 + numxc12 + numxc13 + numxc14 + numxc15)));
        double xc = Double.parseDouble(totXC.getText().trim());
        
        xy1.setText(Double.toString(numx1 * numy1));
        double numxy1 = Double.parseDouble(xy1.getText().trim());
        xy2.setText(Double.toString(numx2 * numy2));
        double numxy2 = Double.parseDouble(xy2.getText().trim());
        xy3.setText(Double.toString(numx3 * numy3));
        double numxy3 = Double.parseDouble(xy3.getText().trim());
        xy4.setText(Double.toString(numx4 * numy4));
        double numxy4 = Double.parseDouble(xy4.getText().trim());
        xy5.setText(Double.toString(numx5 * numy5));
        double numxy5 = Double.parseDouble(xy5.getText().trim());
        xy6.setText(Double.toString(numx6 * numy6));
        double numxy6 = Double.parseDouble(xy6.getText().trim());
        xy7.setText(Double.toString(numx7 * numy7));
        double numxy7 = Double.parseDouble(xy7.getText().trim());
        xy8.setText(Double.toString(numx8 * numy8));
        double numxy8 = Double.parseDouble(xy8.getText().trim());
        xy9.setText(Double.toString(numx9 * numy9));
        double numxy9 = Double.parseDouble(xy9.getText().trim());
        xy10.setText(Double.toString(numx10 * numy10));
        double numxy10 = Double.parseDouble(xy10.getText().trim());
        xy11.setText(Double.toString(numx11 * numy11));
        double numxy11 = Double.parseDouble(xy11.getText().trim());
        xy12.setText(Double.toString(numx12 * numy12));
        double numxy12 = Double.parseDouble(xy12.getText().trim());
        xy13.setText(Double.toString(numx13 * numy13));
        double numxy13 = Double.parseDouble(xy13.getText().trim());
        xy14.setText(Double.toString(numx14 * numy14));
        double numxy14 = Double.parseDouble(xy14.getText().trim());
        xy15.setText(Double.toString(numx15 * numy15));
        double numxy15 = Double.parseDouble(xy15.getText().trim());
        totXY.setText(Double.toString((numxy1 + numxy2 + numxy3 + numxy4 + numxy5 + numxy6 + numxy7 + numxy8
                + numxy9 + numxy10 + numxy11 + numxy12 + numxy13 + numxy14 + numxy15)));
        double xy = Double.parseDouble(totXY.getText().trim());
        
        yc1.setText(Double.toString(numy1 * numy1));
        double numyc1 = Double.parseDouble(yc1.getText().trim());
        yc2.setText(Double.toString(numy2 * numy2));
        double numyc2 = Double.parseDouble(yc2.getText().trim());
        yc3.setText(Double.toString(numy3 * numy3));
        double numyc3 = Double.parseDouble(yc3.getText().trim());
        yc4.setText(Double.toString(numy4 * numy4));
        double numyc4 = Double.parseDouble(yc4.getText().trim());
        yc5.setText(Double.toString(numy5 * numy5));
        double numyc5 = Double.parseDouble(yc5.getText().trim());
        yc6.setText(Double.toString(numy6 * numy6));
        double numyc6 = Double.parseDouble(yc6.getText().trim());
        yc7.setText(Double.toString(numy7 * numy7));
        double numyc7 = Double.parseDouble(yc7.getText().trim());
        yc8.setText(Double.toString(numy8 * numy8));
        double numyc8 = Double.parseDouble(yc8.getText().trim());
        yc9.setText(Double.toString(numy9 * numy9));
        double numyc9 = Double.parseDouble(yc9.getText().trim());
        yc10.setText(Double.toString(numy10 * numy10));
        double numyc10 = Double.parseDouble(yc10.getText().trim());
        yc11.setText(Double.toString(numy11 * numy11));
        double numyc11 = Double.parseDouble(yc11.getText().trim());
        yc12.setText(Double.toString(numy12 * numy12));
        double numyc12 = Double.parseDouble(yc12.getText().trim());
        yc13.setText(Double.toString(numy13 * numy13));
        double numyc13 = Double.parseDouble(yc13.getText().trim());
        yc14.setText(Double.toString(numy14 * numy14));
        double numyc14 = Double.parseDouble(yc14.getText().trim());
        yc15.setText(Double.toString(numy15 * numy15));
        double numyc15 = Double.parseDouble(yc15.getText().trim());
        totYC.setText(Double.toString((numyc1 + numyc2 + numyc3 + numyc4 + numyc5 + numyc6 + numyc7 + numyc8
                + numyc9 + numyc10 + numyc11 + numyc12 + numyc13 + numyc14 + numyc15)));
        double yc = Double.parseDouble(totYC.getText().trim());
        double va = Double.parseDouble(valorAct.getText().trim());
        
        a0.setText(Double.toString(((((y*xc)-(x*xy))/((va*xc)-(x*x))))));
        a1.setText(Double.toString(((((va*xy)-(x*y))/((va*xc)-(x*x))))));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //double ny = Double.parseDouble(valory.getText().trim());
        double numa0 = Double.parseDouble(a0.getText().trim());
        double numa1 = Double.parseDouble(a1.getText().trim());
        double nx = Double.parseDouble(nuevox.getText().trim());
        
        valory.setText(Double.toString(nx));
        valorx.setText(Double.toString(numa0 + (nx * numa1)));
        
        double numx1 = Double.parseDouble(x1.getText().trim());
        nx1.setText(Double.toString(numx1));
        double numx2 = Double.parseDouble(x2.getText().trim());
        nx2.setText(Double.toString(numx2));
        double numx3 = Double.parseDouble(x3.getText().trim());
        nx3.setText(Double.toString(numx3));
        double numx4 = Double.parseDouble(x4.getText().trim());
        nx4.setText(Double.toString(numx4));
        double numx5 = Double.parseDouble(x5.getText().trim());
        nx5.setText(Double.toString(numx5));
        double numx6 = Double.parseDouble(x6.getText().trim());
        nx6.setText(Double.toString(numx6));
        double numx7 = Double.parseDouble(x7.getText().trim());
        nx7.setText(Double.toString(numx7));
        double numx8 = Double.parseDouble(x8.getText().trim());
        nx8.setText(Double.toString(numx8));
        double numx9 = Double.parseDouble(x9.getText().trim());
        nx9.setText(Double.toString(numx9));
        double numx10 = Double.parseDouble(x10.getText().trim());
        nx10.setText(Double.toString(numx10));
        double numx11 = Double.parseDouble(x11.getText().trim());
        nx11.setText(Double.toString(numx11));
        double numx12 = Double.parseDouble(x12.getText().trim());
        nx12.setText(Double.toString(numx12));
        double numx13 = Double.parseDouble(x13.getText().trim());
        nx13.setText(Double.toString(numx13));
        double numx14 = Double.parseDouble(x14.getText().trim());
        nx14.setText(Double.toString(numx14));
        double numx15 = Double.parseDouble(x15.getText().trim());
        nx15.setText(Double.toString(numx15));
        
        ny1.setText(Double.toString((numa0 + numx1) * numa1));
        ny2.setText(Double.toString((numa0 + numx2) * numa1));
        ny3.setText(Double.toString((numa0 + numx3) * numa1));
        ny4.setText(Double.toString((numa0 + numx4) * numa1));
        ny5.setText(Double.toString((numa0 + numx5) * numa1));
        ny6.setText(Double.toString((numa0 + numx6) * numa1));
        ny7.setText(Double.toString((numa0 + numx7) * numa1));
        ny8.setText(Double.toString((numa0 + numx8) * numa1));
        ny9.setText(Double.toString((numa0 + numx9) * numa1));
        ny10.setText(Double.toString((numa0 + numx10) * numa1));
        ny11.setText(Double.toString((numa0 + numx11) * numa1));
        ny12.setText(Double.toString((numa0 + numx12) * numa1));
        ny13.setText(Double.toString((numa0 + numx13) * numa1));
        ny14.setText(Double.toString((numa0 + numx14) * numa1));
        ny15.setText(Double.toString((numa0 + numx15) * numa1));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegresionLineal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a0;
    private javax.swing.JTextField a1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nuevox;
    private javax.swing.JTextField nx1;
    private javax.swing.JTextField nx10;
    private javax.swing.JTextField nx11;
    private javax.swing.JTextField nx12;
    private javax.swing.JTextField nx13;
    private javax.swing.JTextField nx14;
    private javax.swing.JTextField nx15;
    private javax.swing.JTextField nx2;
    private javax.swing.JTextField nx3;
    private javax.swing.JTextField nx4;
    private javax.swing.JTextField nx5;
    private javax.swing.JTextField nx6;
    private javax.swing.JTextField nx7;
    private javax.swing.JTextField nx8;
    private javax.swing.JTextField nx9;
    private javax.swing.JTextField ny1;
    private javax.swing.JTextField ny10;
    private javax.swing.JTextField ny11;
    private javax.swing.JTextField ny12;
    private javax.swing.JTextField ny13;
    private javax.swing.JTextField ny14;
    private javax.swing.JTextField ny15;
    private javax.swing.JTextField ny2;
    private javax.swing.JTextField ny3;
    private javax.swing.JTextField ny4;
    private javax.swing.JTextField ny5;
    private javax.swing.JTextField ny6;
    private javax.swing.JTextField ny7;
    private javax.swing.JTextField ny8;
    private javax.swing.JTextField ny9;
    private javax.swing.JTextField totX;
    private javax.swing.JTextField totXC;
    private javax.swing.JTextField totXY;
    private javax.swing.JTextField totY;
    private javax.swing.JTextField totYC;
    private javax.swing.JTextField valorAct;
    private javax.swing.JTextField valorx;
    private javax.swing.JTextField valory;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x10;
    private javax.swing.JTextField x11;
    private javax.swing.JTextField x12;
    private javax.swing.JTextField x13;
    private javax.swing.JTextField x14;
    private javax.swing.JTextField x15;
    private javax.swing.JTextField x2;
    private javax.swing.JTextField x3;
    private javax.swing.JTextField x4;
    private javax.swing.JTextField x5;
    private javax.swing.JTextField x6;
    private javax.swing.JTextField x7;
    private javax.swing.JTextField x8;
    private javax.swing.JTextField x9;
    private javax.swing.JTextField xc1;
    private javax.swing.JTextField xc10;
    private javax.swing.JTextField xc11;
    private javax.swing.JTextField xc12;
    private javax.swing.JTextField xc13;
    private javax.swing.JTextField xc14;
    private javax.swing.JTextField xc15;
    private javax.swing.JTextField xc2;
    private javax.swing.JTextField xc3;
    private javax.swing.JTextField xc4;
    private javax.swing.JTextField xc5;
    private javax.swing.JTextField xc6;
    private javax.swing.JTextField xc7;
    private javax.swing.JTextField xc8;
    private javax.swing.JTextField xc9;
    private javax.swing.JTextField xy1;
    private javax.swing.JTextField xy10;
    private javax.swing.JTextField xy11;
    private javax.swing.JTextField xy12;
    private javax.swing.JTextField xy13;
    private javax.swing.JTextField xy14;
    private javax.swing.JTextField xy15;
    private javax.swing.JTextField xy2;
    private javax.swing.JTextField xy3;
    private javax.swing.JTextField xy4;
    private javax.swing.JTextField xy5;
    private javax.swing.JTextField xy6;
    private javax.swing.JTextField xy7;
    private javax.swing.JTextField xy8;
    private javax.swing.JTextField xy9;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y10;
    private javax.swing.JTextField y11;
    private javax.swing.JTextField y12;
    private javax.swing.JTextField y13;
    private javax.swing.JTextField y14;
    private javax.swing.JTextField y15;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField y4;
    private javax.swing.JTextField y5;
    private javax.swing.JTextField y6;
    private javax.swing.JTextField y7;
    private javax.swing.JTextField y8;
    private javax.swing.JTextField y9;
    private javax.swing.JTextField yc1;
    private javax.swing.JTextField yc10;
    private javax.swing.JTextField yc11;
    private javax.swing.JTextField yc12;
    private javax.swing.JTextField yc13;
    private javax.swing.JTextField yc14;
    private javax.swing.JTextField yc15;
    private javax.swing.JTextField yc2;
    private javax.swing.JTextField yc3;
    private javax.swing.JTextField yc4;
    private javax.swing.JTextField yc5;
    private javax.swing.JTextField yc6;
    private javax.swing.JTextField yc7;
    private javax.swing.JTextField yc8;
    private javax.swing.JTextField yc9;
    // End of variables declaration//GEN-END:variables
}
